apiVersion: v1
kind: Service
metadata:
  name: flask-app
  labels:
    app: flask-app
spec:
  # LoadBalancer : DigitalOcean provisionne automatiquement un LB avec une IP publique externe.
  # Pour éviter le coût du LB, remplacer "LoadBalancer" par "NodePort" (voir SETUP-DIGITALOCEAN.md).
  type: LoadBalancer
  selector:
    app: flask-app
  ports:
    - name: http
      port: 80
      targetPort: 5000
